modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "bluemap_viewer"
version = "${version}"
displayName = "Bluemap Viewer"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.bluemap_viewer]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bluemap_viewer]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bluemap_viewer]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bluemap_viewer.mixins.json"
